package com.ziemozi;


import com.codename1.components.ToastBar;

import static com.codename1.io.ConnectionRequest.setDefaultCacheMode;

import com.codename1.io.ConnectionRequest;
import com.codename1.system.DefaultCrashReporter;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.ziemozi.server.ServerAPI;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.io.Preferences;
import com.codename1.push.Push;
import com.codename1.push.PushCallback;

import static com.codename1.io.Log.REPORTING_DEBUG;

import com.codename1.ui.Display;

import com.ziemozi.ziemozi.UIController;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Ziemozi implements PushCallback {

    private Form current;
    private Resources theme;
    //public StartAppManager manager;
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);
        //
        //initialize random number generatr
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
        Log.setReportingLevel(Log.REPORTING_DEBUG);
        DefaultCrashReporter.init(true, 2);
        theme = UIManager.initFirstTheme("/theme");
        //manager = new StartAppManager();
       // manager.initAndroidSDK("200083762", "141359216", true);
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        //manager.loadAd(StartAppManager.AD_INTERSTITIALS);
        // Pro only feature
        Log.bindCrashProtection(true);
        Log.setReportingLevel(REPORTING_DEBUG);

        setDefaultCacheMode(ConnectionRequest.CachingMode.OFF);
      
addNetworkErrorListener(err -> {
            // prevent the event from propagating
            //////Log.p(err.getMessage());
            Log.sendLogAsync();
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            ToastBar.showErrorMessage("Network not availavle");
        }
        
        );

    }

    public void start() {
        if (current != null) {

            current.show();
            return;
        }

        UIController.showSplashScreen();

        if (ServerAPI.isLoggedIn()) {
            //manager.showAd();
            callSerially(() -> registerPush());
        }

    }

    public void stop() {
        //ToastBar.showInfoMessage("Syncing with Server");
        //ServerAPI.loadToLocalDatabase();
        //localAPI.saveRequestsToServer(); 

        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }

    }

    public void destroy() {
    }

    @Override
    public void push(String value) {
        UIController.refresh();
    }

    @Override
    public void registeredForPush(String deviceId) {
        String pk = Preferences.get("pushkey", "");
        if (!pk.equals(Push.getPushKey())) {
            if (ServerAPI.updatePushKey(pk)) {
                Preferences.set("pushkey", Push.getPushKey());
            }
        }
    }

    @Override
    public void pushRegistrationError(String error, int errorCode) {
        //////Log.p("Failed to register for push: " + error);
    }

    
}
